# Generated by Django 3.2.6 on 2021-08-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_component_componentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(default='', upload_to='upload/'),
        ),
    ]
