# Generated by Django 3.2.6 on 2021-08-12 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_component_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.FileField(default='', upload_to='upload/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])]),
        ),
    ]
