# Generated by Django 3.2.6 on 2021-08-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_component_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.TextField()),
            ],
        ),
    ]
