# Generated by Django 3.2.6 on 2021-08-15 17:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_samplecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='docscategory',
            name='component',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.component'),
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.FileField(default='', upload_to='upload/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])]),
        ),
    ]
