# Generated by Django 3.2.6 on 2021-08-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210815_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
    ]
