# Generated by Django 3.2.6 on 2021-08-16 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_component_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='docs_file',
            field=models.FileField(default='', upload_to='upload/files/', validators=[django.core.validators.FileExtensionValidator(['zip', 'rar'])]),
        ),
    ]
